"""
metrics_utils.py — Shared evaluation metrics for VulnLocAI.

All metric definitions are taken directly from the paper:
  "VulnLocAI: Bridging the Semantic-Syntactic Gap for Precise Vulnerability
   Localization via Instruction-Tuned Generative Models"

Metrics implemented
-------------------
Classification:
  - Precision  = TP / (TP + FP)
  - Recall     = TP / (TP + FN)
  - F1-score   = 2 * P * R / (P + R)
  - Accuracy   = (TP + TN) / (TP + TN + FP + FN)

Localization:
  - Top-1 Accuracy: prediction is a HIT if the predicted line text appears
                    anywhere within the ground-truth vulnerable line range.
  - Exact Match (EM): predicted line == ground-truth line (string equality
                      after normalisation).

Output parsing:
  - Model output format (vulnerable):  "CWE-XX, <exact vulnerable line>, <description>"
  - Model output format (benign):      "No vulnerability detected. The code is secure."
"""

import re
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score


# ---------------------------------------------------------------------------
# Output parsing
# ---------------------------------------------------------------------------

def parse_model_output(raw_output: str) -> dict:
    """
    Parse the raw text generated by VulnLocAI (or any baseline) into structured
    fields, following the Alpaca output format defined in Table 2 of the paper.

    Returns a dict with keys:
        predicted_label      : "vulnerable" or "benign"
        predicted_cwe        : e.g. "CWE-78"  (None for benign)
        predicted_line       : exact vulnerable line text (None for benign)
        predicted_description: explanation text (None for benign)
        raw                  : original raw output (for debugging)
    """
    text = raw_output.strip()

    # Benign prediction
    benign_markers = [
        "no vulnerability detected",
        "no vulnerability",
        "the code is secure",
        "benign",
    ]
    if any(m in text.lower() for m in benign_markers):
        return {
            "predicted_label": "benign",
            "predicted_cwe": None,
            "predicted_line": None,
            "predicted_description": None,
            "raw": text,
        }

    # Vulnerable prediction — expected format: "CWE-XX, <line>, <description>"
    # The CWE ID is always the first token before the first comma.
    cwe_match = re.match(r"(CWE-\d+)", text, re.IGNORECASE)
    predicted_cwe = cwe_match.group(1).upper() if cwe_match else None

    # Extract line and description by splitting on the first two commas
    parts = text.split(",", 2)
    if len(parts) >= 2:
        predicted_line = parts[1].strip()
        predicted_description = parts[2].strip() if len(parts) > 2 else ""
    else:
        # Fallback: treat entire text as the predicted line
        predicted_line = text
        predicted_description = ""

    return {
        "predicted_label": "vulnerable",
        "predicted_cwe": predicted_cwe,
        "predicted_line": predicted_line,
        "predicted_description": predicted_description,
        "raw": text,
    }


def _normalise(s: str) -> str:
    """Strip whitespace and collapse internal spaces for fair string comparison."""
    return re.sub(r"\s+", " ", str(s)).strip().lower()


# ---------------------------------------------------------------------------
# Localization metrics
# ---------------------------------------------------------------------------

def top1_accuracy(predictions: list[dict], ground_truth_df: pd.DataFrame) -> float:
    """
    Top-1 Line Accuracy:
      A prediction is a HIT if the predicted line text is contained within
      (or equals) the ground-truth 'Exact Vulnerable Line' for that sample.

    Only evaluated over the subset where:
      - ground truth label is 'vulnerable'
      - model also predicted 'vulnerable' (i.e. true positives)
    """
    hits, total = 0, 0
    for pred, (_, row) in zip(predictions, ground_truth_df.iterrows()):
        if str(row["Status"]).lower() != "vulnerable":
            continue
        if pred["predicted_label"] != "vulnerable":
            continue  # false negative — not counted in localization denominator
        total += 1
        gt_line = _normalise(row["Exact Vulnerable Line"])
        pred_line = _normalise(pred["predicted_line"] or "")
        # HIT if predicted line is a substring of the GT line or vice-versa
        if pred_line and (pred_line in gt_line or gt_line in pred_line):
            hits += 1
    return hits / total if total > 0 else 0.0


def exact_match(predictions: list[dict], ground_truth_df: pd.DataFrame) -> float:
    """
    Exact Match — EM (Equation 4 of the paper):
      EM = (1/N) * sum_i δ(P_i, G_i)
      where δ(x, y) = 1 if x == y (after normalisation), 0 otherwise.

    Only evaluated over all vulnerable samples in the benchmark (regardless
    of whether the model predicted vulnerable or benign).
    """
    matches, total = 0, 0
    for pred, (_, row) in zip(predictions, ground_truth_df.iterrows()):
        if str(row["Status"]).lower() != "vulnerable":
            continue
        total += 1
        if pred["predicted_label"] != "vulnerable":
            continue
        gt_line = _normalise(row["Exact Vulnerable Line"])
        pred_line = _normalise(pred["predicted_line"] or "")
        if pred_line == gt_line:
            matches += 1
    return matches / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# Classification metrics
# ---------------------------------------------------------------------------

def compute_classification_metrics(predictions: list[dict],
                                   ground_truth_df: pd.DataFrame) -> dict:
    """
    Compute Precision, Recall, F1, and Accuracy (Equations 1-3 of the paper).

    Binary labels: 'vulnerable' → 1,  'benign' → 0
    """
    y_true = [1 if str(r["Status"]).lower() == "vulnerable" else 0
              for _, r in ground_truth_df.iterrows()]
    y_pred = [1 if p["predicted_label"] == "vulnerable" else 0
              for p in predictions]

    return {
        "Precision": round(precision_score(y_true, y_pred, zero_division=0) * 100, 1),
        "Recall":    round(recall_score(y_true, y_pred, zero_division=0) * 100, 1),
        "F1":        round(f1_score(y_true, y_pred, zero_division=0) * 100, 1),
        "Accuracy":  round(accuracy_score(y_true, y_pred) * 100, 1),
    }


def compute_all_metrics(predictions: list[dict],
                        ground_truth_df: pd.DataFrame,
                        model_name: str = "Model") -> dict:
    """
    Compute and print all metrics reported in the paper (Table 3, Figure 3).

    Returns a dict suitable for building comparison tables.
    """
    clf = compute_classification_metrics(predictions, ground_truth_df)
    top1 = round(top1_accuracy(predictions, ground_truth_df) * 100, 1)
    em   = round(exact_match(predictions, ground_truth_df) * 100, 1)

    results = {
        "Model":      model_name,
        "Precision":  clf["Precision"],
        "Recall":     clf["Recall"],
        "F1":         clf["F1"],
        "Accuracy":   clf["Accuracy"],
        "Top1":       top1,
        "EM":         em,
    }

    print(f"\n{'='*55}")
    print(f"  Results for: {model_name}")
    print(f"{'='*55}")
    print(f"  Precision :  {clf['Precision']}%")
    print(f"  Recall    :  {clf['Recall']}%")
    print(f"  F1-Score  :  {clf['F1']}%")
    print(f"  Accuracy  :  {clf['Accuracy']}%")
    print(f"  Top-1 Acc :  {top1}%")
    print(f"  Exact Match: {em}%")
    print(f"{'='*55}\n")
    return results
